"""add operation_count to course_student

Revision ID: 924886b209da
Revises: be77e7b8ca2e
Create Date: 2025-06-13 10:57:36.680423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924886b209da'
down_revision = 'be77e7b8ca2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_student', schema=None) as batch_op:
        batch_op.drop_column('operation_count')

    # ### end Alembic commands ###
